### ISSUE TITLE
Akari走了，我该怎么做

### ISSUE THREAD

**Issue by angushushu** [AkariDream/CubeX-Log#101]
涉及玩家：angushushu
处理人：AkariDream
事件描述：Akari走了，作为小白的我应该怎样系统学习代理，正版验证，网络防护，以及反作弊等相关知识？Akari，我会时刻想念你。
处理结果：坚守“先这样 再那样”原则

**Comment by AkariDream** [comment]
先这样 再那样

**Comment by angushushu** [comment]
很有用，常联系

**Comment by doudouCodingInGithub** [comment]
啊这
