### ISSUE TITLE
[Bug] Purpur未检测到Spark

### ISSUE THREAD

**Issue by AkariDream** [AkariDream/CubeX-Log#102]
每次开启服务端都会停止主线程然后下载所需内容
导致服务器启动速度缓慢. 甚至导致可能的卡死
详见 ![此处](https://github.com/PurpurMC/Purpur/issues/1249)

**Comment by Kianakiferi** [comment]
昨儿晚上七点 （2023-0122 19:47:20），开发者 [granny](https://github.com/granny) 为 Purpur 检测 Spark 的行为添加了适当的（5000毫秒）延时，关闭了该 [issue](https://github.com/PurpurMC/Purpur/issues/1249) ，详细请见 [commit 4226787](https://github.com/PurpurMC/Purpur/commit/42267870c290d2c74b0debdbf1e931f5b808777a)，已在 [Build 1901](https://purpurmc.org/downloads) 中发布。
我实际启动也没有再出现超长延时，现在这个问题应该无感了

**Comment by AkariDream** [comment]
> 昨儿晚上七点 （2023-0122 19:47:20），开发者 [granny](https://github.com/granny) 为 Purpur 检测 Spark 的行为添加了适当的（5000毫秒）延时，关闭了该 [issue](https://github.com/PurpurMC/Purpur/issues/1249) ，详细请见 [commit 4226787](https://github.com/PurpurMC/Purpur/commit/42267870c290d2c74b0debdbf1e931f5b808777a)，已在 [Build 1901](https://purpurmc.org/downloads) 中发布。 我实际启动也没有再出现超长延时，现在这个问题应该无感了

我甚至已经忘记了这个问题 :| 当然 我知道已经发布了 但是为了保险 我还会过一段时间再考虑升级
