### ISSUE TITLE
修改Iris World Gen的宝藏分配

### ISSUE THREAD

**Issue by angushushu** [AkariDream/CubeX-Log#33]
涉及玩家：Null
处理人：
事件描述：当前资源世界宝藏比较丰富，需要修改iris世界。另外有没有必要用myworlds替换multiverse（iris world gen文档里建议）？
处理结果：

**Comment by AkariDream** [comment]
请添加tag

**Comment by angushushu** [comment]
~test

**Comment by AkariDream** [comment]
请尽快完成需要处理的东西. 否则此issue将关闭

**Comment by angushushu** [comment]
可以改世界目录下的paper文件，但是特殊物品什么的估计要在生存前配置
