### ISSUE TITLE
基岩玩家ncp兼容问题

### ISSUE THREAD

**Issue by angushushu** [AkariDream/CubeX-Log#38]
涉及玩家：基岩玩家
处理人：
事件描述：重新配置floodgate和geyser后，基岩玩家在箱子上会被误判ncp的MOVING_SURVIVALFLY，但是cncp里面已经except了。不知道跟floodgate配置有没有关系（send-floodgate-data）,不过那个梦什么的反作弊是可以检测到玩家来自geyser的。
处理结果：暂时对所有基岩玩家做/ncp exempt MOVING_SURVIVALFLY

**Comment by angushushu** [comment]
补充：不知MOVING_SURVIVALFLY, 暂时exempt all了

**Comment by angushushu** [comment]
- [x] 修改floodgate，重新设置key
- [ ] 重启BC，生存，AuthX，Practice，Rouge
- [ ] 检查基岩版是否正常以及作弊兼容
- [ ] 不能进入的话恢复原状

**Comment by angushushu** [comment]
现开启send-floodgate-data可正常进入，但是ncp兼容仍有问题。仍然会卡在箱子上（cncp好像没有生效？），开启/ncp unexempt all可解决。暂时对基岩玩家exempt creativefly意外所有检查。

**Comment by AkariDream** [comment]
可以考虑为生存安装Spartan 但是只能作为辅助使用

**Comment by angushushu** [comment]
> 可以考虑为生存安装Spartan 但是只能作为辅助使用

之前是不是装过？

**Comment by AkariDream** [comment]
> > 可以考虑为生存安装Spartan 但是只能作为辅助使用
> 
> 之前是不是装过？

现在没有

**Comment by AkariDream** [comment]
目前看来NCP并没有问题. 如需继续讨论请新开issue
