### ISSUE TITLE
simple voice chat

### ISSUE THREAD

**Issue by angushushu** [AkariDream/CubeX-Log#39]
涉及玩家：填Null
处理人：angushushu
事件描述：用不了svc
处理结果：联系客服开启24454/udp，效果待观察

**Comment by angushushu** [comment]
10/27仍然显示通话不可用，会联系客服然后等下次重启再试

**Comment by AkariDream** [comment]
确保指定客户端没有使用ViaVersions

**Comment by angushushu** [comment]
经检查应该是海外线路没开通24454，国内线路正常

**Comment by angushushu** [comment]
海外线路不支持udp端口，寄
