### ISSUE TITLE
生存Practice经济互通

### ISSUE THREAD

**Issue by angushushu** [AkariDream/CubeX-Log#40]
涉及玩家：Null
处理人：AkariDream, angushushu
事件描述：通过playerpoint连接实现practice和survival经济互通
- [x] 开设playerpoint mysql db
- [x] 生存安装playerpoint

**Comment by angushushu** [comment]
当前生存服playerpoints和essential economy是分开的，不确定如何绑定。

**Comment by AkariDream** [comment]
> 当前生存服playerpoints和essential economy是分开的，不确定如何绑定。

`Default Config` `line:14` `vault: true`

**Comment by angushushu** [comment]
> > 当前生存服playerpoints和essential economy是分开的，不确定如何绑定。
> 
> `Default Config` `line:14` `vault: true`

现在就这么配置的

**Comment by AkariDream** [comment]
考虑制作菜单与PlayerPoints绑定.

**Comment by angushushu** [comment]
> 考虑制作菜单与PlayerPoints绑定.

有个问题，如果bal余额不足，怎么阻止执行添加points的操作？

**Comment by AkariDream** [comment]
DeluxeMenus有Price: number 属性

**Comment by AkariDream** [comment]
*应该 反正ChestCommand有

**Comment by angushushu** [comment]
生存的点卷商店好了，/dmshop访问，确认后我就在指令菜单里开放。另外是不是practice的playerpoints需要挂一下vps的mysql？

**Comment by AkariDream** [comment]
私发
