### ISSUE TITLE
坐在任何载具上会有概率被踢出并显示You're sending too many packets :(

### ISSUE THREAD

**Issue by doudouCodingInGithub** [AkariDream/CubeX-Log#58]
### 问题
坐在任何载具上会有概率被踢出并显示You're sending too many packets :(

### 复现
骑乘任意载具(如羊驼，船)
等待(船的概率很高)
被踢出并显示You're sendinng too many packets :(

### 期望
不被踢出

### 媒体
[Minecraft_1.19.2 - 多人游戏（第三方服务器） 2022-11-08 19-19-15.mp4]

### 客户端信息:
Edition: Java
版本: 1.19
客户端标识: Fabric

### 附加信息
无

**Comment by doudouCodingInGithub** [comment]
完了，忘了贴tag了

**Comment by AkariDream** [comment]
该情况不属于ACFP. 请问能不能带视频录制或者其它的一些证据?

**Comment by AkariDream** [comment]
在discord上面打开ticket有助于更好的说明你遇到的情况

**Comment by doudouCodingInGithub** [comment]
已放在QQ群中：Minecraft_ 1.19.2 - 多人游戏（第三方服务器） 2022-11-08 19-19-15.mp4

**Comment by AkariDream** [comment]
需要重启服务器以应用更改 请在下一次自动重启之后再次尝试 关闭issue表示已解决.

**Comment by doudouCodingInGithub** [comment]
# 谢谢

**Comment by AkariDream** [comment]
我的意思是 你先试了解决了再说(

**Comment by doudouCodingInGithub** [comment]
淦 等重启吧

**Comment by AkariDream** [comment]
@doudouCodingInGithub

**Comment by AkariDream** [comment]
如果此issue在 GMT+8 22-11-13 12:00未响应 代表已经解决不需要进一步讨论
