### ISSUE TITLE
[ACFP]

### ISSUE THREAD

**Issue by Z1iiii** [AkariDream/CubeX-Log#72]
**描述问题本身**
越简略越好

**复现**
1. 复现条件 '...'
2. 先这样 '....'
3. 再那样 '....'
4. 被警告或被封禁.

**期望**
简介描述你想如何让反作弊达到预期的目的

**媒体**
如果可能 请上传截图/视频帮助我们更好的判断错误所在

**客户端信息:**
 - Edition: Java/Bedrock
 - 版本: 当前游戏版本号(或客户端协议号)
 - 客户端标识: Vanilla, Forge, Fabric, Fml Forge(LegacyForge), Lunarclient等

**附加信息**
在此填入任何你想添加的信息
Z1iiii

**Comment by AkariDream** [comment]
不要打开与tag无关的问题 如果多次这么做你可能会被剥夺打开issue的权利.
