### ISSUE TITLE
hewenhao屠杀study的图书管理员

### ISSUE THREAD

**Issue by angushushu** [AkariDream/CubeX-Log#83]
#Daily #谋杀
涉及玩家：study, hewenhao
处理人：angushushu
事件描述：hewenhao杀了study jys的15个图书管理员
处理结果：通过指令恢复中，贼麻烦。MFWulin在负责对hewenhao的处罚。

**Comment by doudouCodingInGithub** [comment]
# wc

**Comment by angushushu** [comment]
恢复了，不知道mf怎么处罚的

**Comment by doudouCodingInGithub** [comment]
### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### wow

**Comment by doudouCodingInGithub** [comment]
# hewenhao的滔天大罪
### _**hewenhao屠杀study的图书管理员**_
