### ISSUE TITLE
hologram频繁消失问题

### ISSUE THREAD

**Issue by angushushu** [AkariDream/CubeX-Log#89]
#plugins
涉及玩家：Null
处理人：Null
事件描述：DecentHolograms的holograms经常消失，要reload才可见（authx和survival）。
处理结果：考虑换回holographical display试试
对了给我加到collaborator里，这样就能加label了
@AkariDream

**Comment by AkariDream** [comment]
这些可能与entityid相关. 并且并不建议全息图
如果是最近更新的DecentHolograms或者ProtocolLib 则可以考虑更新两者还有via 看看问题是否依然存在

**Comment by angushushu** [comment]
Q
